# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|

  config.vm.guest = :freebsd
  config.vm.synced_folder ".", "/vagrant", id: "vagrant-root", disabled: true
  config.vm.box = "freebsd/FreeBSD-10.3-RELEASE"
  config.ssh.shell = "sh"
  config.vm.base_mac = "080027D14C66"

  config.vm.provider :virtualbox do |vb|
    vb.customize ["modifyvm", :id, "--memory", "1024"]
    vb.customize ["modifyvm", :id, "--cpus", "4"]
    vb.customize ["modifyvm", :id, "--hwvirtex", "on"]
    vb.customize ["modifyvm", :id, "--audio", "none"]
    vb.customize ["modifyvm", :id, "--nictype1", "virtio"]
    vb.customize ["modifyvm", :id, "--nictype2", "virtio"]
  end

  config.vm.provision "shell", inline: <<-SHELL
    pkg install -y git cmake pcre protobuf protobuf-c libev libredblack valgrind
  SHELL

  config.vm.provision "shell", inline: <<-SHELL
    if [ ! -d "cmocka" ]; then
      git clone git://git.cryptomilk.org/projects/cmocka.git
	  cd cmocka; mkdir build; cd build
	  cmake .. && make -j4
	  make install
	  cd ../..
	fi
  SHELL

  config.vm.provision "shell", inline: <<-SHELL
    rm -rf libyang
    git clone https://github.com/CESNET/libyang.git
	cd libyang; mkdir build; cd build
	cmake .. && make -j4
	make install
	cd ../..
  SHELL

  config.vm.provision "shell", inline: <<-SHELL
    rm -rf sysrepo
    git clone https://github.com/sysrepo/sysrepo.git
	cd sysrepo; mkdir build; cd build
	cmake .. && make -j4
	make install
	cd ../..
  SHELL

end
